spring:
  application:
    name: JomaJomaDelivery
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/joma
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

        registration:
          naver:
            client-id: iUUHltDBSq8BCxdIWlTz
            client-secret: pVY9_B7bk2
            client-name: Naver
            scope:
              - name
              - email
            redirect-uri: http://localhost:8080/login/oauth2/code/home
            authorization-grant-type: authorization_code


